taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path("SiteApp/", include("SiteApp.urls", namespace="SiteApp")),

    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

taskmanager/users/urls.py
from django.urls import path
from .views import register, profile, seller_profile
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

app_name = "users"

urlpatterns = [
    path('register/', register, name="register"),
    path('login/', LoginView.as_view(template_name = "users/login.html"), name="login"),
    path('logout/', TemplateView.as_view(template_name = "users/logout.html"), name="logout"),
    path('profile/', profile, name="profile"),
    path('sellerprofile/<int:id>/', seller_profile, name="sellerprofile"),

]

taskmanager/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to="_profile_images")
    contact_number = models.CharField(max_length=50, default="+79281234567")

    def __str__(self):
        return str(self.user.username)

taskmanager/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={"class":"focus:outline-none", "placeholder":"mail@mail.com"}))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={"class":"focus:outline-none", "placeholder":"Your name"}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={"class":"focus:outline-none", "placeholder":"Password"}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={"class":"focus:outline-none", "placeholder":"Confirm Password"}))


    class Meta:
        model = User
        fields = ("username", "email",  "password1", "password2")

    #def save(self, commit=True):
    #    user = super(NewUserForm, self).save(commit=False)
    #    user.email = self.cleaned_data["email"]
    #    if commit:
    #        user.save()
    #    return user

taskmanager/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("SiteApp:index")
    form = NewUserForm()
    context = {'form':form}
    return render(request, 'users/register.html', context)

@login_required
def profile(request):
    return render(request, "users/profile.html")

def seller_profile(request, id):
    seller = User(id=id)

    context = {
        'seller': seller
    }

    return render(request, "users/sellerprofile.html", context)

taskmanager/users/templates/users/login.html
{% extends "SiteApp/base.html" %}

{% block content %}

<div class="container py-5">
    <h1 class="text-2xl m-10 font-bold">Login Users</h1>
    <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-2 ">
            <label class="block text-black-500 text-sm font-bold mb-2">Username</label>
            <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-black-500 leading-tight">{{form.username}}</p>
            <label class="block text-black-500 text-sm font-bold mt-5 mb-2">Password</label>
            <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-black-500 leading-tight">{{form.password}}</p>
        </div>
        <button class="bg-gray-400 text-black px-5 py-2" type="submit">Login</button>
        <button class="bg-gray-400 text-black px-5 py-2"><a href="{% url 'users:register' %}">Register?</a></button>
    </form>
</div>

{% endblock content %}

taskmanager/users/templates/users/logout.html
{% extends "SiteApp/base.html" %}

{% block content %}
    <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit">logout</button>
        <h1>Your have been logout</h1>
    </form>
{% endblock content %}

taskmanager/users/templates/users/profile.html
{% extends "SiteApp/base.html" %}

{% block content %}

    {% if user.profile %}
    <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
        <div class="rounded shadow-lg">
            <div>
                {% if user.profile.image %}
                <img src="{{ user.profile.image.url }}" alt="" srcset="">
                {% endif %}
            </div>
            <h1 class="font-bold text-xl m-2">{{user.username}}</h1>
        </div>
    </div>
    {% else %}
        <h1>
            <form action="" method="post">
                <h1>FORM Profile</h1>
            </form>
        </h1>
    {% endif %}

{% endblock content %}

taskmanager/users/templates/users/register.html
{% extends "SiteApp/base.html" %} 
 
{% block content %} 
 
<div class="container py-5"> 
    <h1 class="text-2xl mb-8 font-bold text-center">Register Users</h1> 
    <form class="w-full max-w-md mx-auto bg-gray-700 shadow-md rounded px-8 pt-6 pb-8" method="post"> 
        {% csrf_token %} 
        <div class="mb-4"> 
            <label class="block text-white text-sm font-bold mb-2" for="username">Username</label> 
            <p class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{form.username}}</p>
        </div> 
        <div class="mb-4"> 
            <label class="block text-white text-sm font-bold mb-2" for="email">Email</label> 
            <p class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{form.email}}</p>
        </div> 
        <div class="mb-4"> 
            <label class="block text-white text-sm font-bold mb-2" for="password1">Password</label> 
            <p class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{form.password1}}</p>
        </div> 
        <div class="mb-4"> 
            <label class="block text-white text-sm font-bold mb-2" for="password2">Confirm Password</label> 
            <p class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{form.password2}}</p>
        </div> 
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit"> 
            Register 
        </button> 
    </form> 
</div> 
 
{% endblock content %}

taskmanager/users/templates/users/sellerprofile.html
{% extends "SiteApp/base.html" %}

{% block content %}

        <h1>SellerProfile</h1>

{% endblock content %}