taskmanager/SiteApp/urls.py
from django.urls import path
from SiteApp import views

app_name = "SiteApp"

urlpatterns = [
    path('', views.index, name="index"),
    #path('', views.ProductListView.as_view(), name="index"),
    #path('<int:item_id>/', views.indexItem, name="detail"),
    path('<int:pk>/', views.ProductDetailView.as_view(), name="detail"),
    path('additem/', views.add_item, name="add_item"),
    path('updateitem/<int:item_id>/', views.update_item, name="update_item"),
    path('deleteitem/<int:pk>/', views.ProductDeleteView.as_view(), name="delete_item"),
    path('success/', views.PaymentSuccessView.as_view(), name="success"),
    path('failed/', views.PaymentFailedView.as_view(), name="failed"),
    path('api/checkout-session/<int:id>/', views.update_item, name="api_checkout_session"),
    #path('mainpage/', views.mainpage),
]

taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path("SiteApp/", include("SiteApp.urls", namespace="SiteApp")),

    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

taskmanager/users/urls.py
from django.urls import path
from .views import register, profile, seller_profile
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

app_name = "users"

urlpatterns = [
    path('register/', register, name="register"),
    path('login/', LoginView.as_view(template_name = "users/login.html"), name="login"),
    path('logout/', TemplateView.as_view(template_name = "users/logout.html"), name="logout"),
    path('profile/', profile, name="profile"),
    path('sellerprofile/<int:id>/', seller_profile, name="sellerprofile"),

]

taskmanager/SiteApp/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default="1")
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    description = models.CharField(max_length=150)
    image = models.ImageField(blank=True, upload_to="images")

    def __str__(self):
        return self.name 
    
class OrderDetail(models.Model):
    customer_username = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    amount = models.IntegerField()
    stripe_payment_intent = models.CharField(max_length=200)
    has_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

taskmanager/SiteApp/views.py
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render 
from django.urls import reverse, reverse_lazy 
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import DeleteView

from .models import Product, OrderDetail

def index(request):
    page_obj=item = Product.objects.all()

    item_name = request.GET.get("search")
    if item_name != '' and item_name is not None:
        page_obj = item.filter(name__icontains=item_name)

    paginator = Paginator(page_obj, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "items":item, "page_obj":page_obj
    }
    return render(request, "SiteApp/index.html", context)

class ProductListView(ListView):
    model = Product
    template_name = "SiteApp/index.html"
    context_object_name = "items"
    paginate_by = 3

#def indexItem(request, item_id):
 #   items = Product.objects.get(id=item_id)
  #  context = {
  #      "item":items
  #  }
  #  return render(request, "SiteApp/detail.html", context=context)

class ProductDetailView(DetailView):
    model = Product
    template_name = "SiteApp/detail.html"
    context_object_name = "item"
    pk_url_kwarg = "pk"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context["stripe_publishable_key"] = settings.STRIPE_PUBLISHABLE_KEY
        return context

@login_required
def add_item(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES["upload"]
        seller = request.user
        item = Product(name=name, price=price, description=description, image=image, seller=seller)
        item.save()
    return render(request, "SiteApp/additem.html")

def update_item(request, item_id):
    item = Product.objects.get(id=item_id)
    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get("upload", item.image)
        item.save()
        return redirect("/SiteApp/")
    context = {
        "item":item
    }
    return render(request, "SiteApp/updateitem.html", context)

def delete_item(request, item_id):
    item = Product.objects.get(id=item_id)
    if request.method == "POST":
        item.delete()
        return redirect("/SiteApp/")
    context = {
        "item":item
    }
    return render(request, "SiteApp/deleteitem.html", context)

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("SiteApp:index")

@csrf_exempt
def create_checkout_session(request, id):
    product = get_object_or_404(Product, pk=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session=stripe.checkout.Session.create(
        customer_email = request.user.email,
        payment_method_types = ["card"],
        line_items = [
            {
                "price_data":{
                    "currency":"usd",
                    "product_data":{
                        "name":product.name,
                    },
                    "unit_amount":int(product.price*100)
                },
                "quantity":1,
            }
        ],
        mode="payment",
        success_url=request.build_absolute_uri(reverse("SiteApp:success"))+"?session_id+{CHECKOUT_SESSION_ID}",
        cancel_url=request.build_absolute_uri(reverse("SiteApp:failed")),
    )
    order = OrderDetail()
    order.customer_username = request.user.username
    order.product = product
    order.stripe_payment_intent = checkout_session["payment_intent"]
    order.amount = int(product.price*100)
    order.save()
    return JsonResponse({"sessionId":checkout_session.id})


class PaymentSuccessView(TemplateView):
    template_name = "SiteApp/payment_success.html"

    def get(self, request, *args, **kwargs):
        session_id = request.GET.get("session_id")
        if session_id is None:
            return HttpResponseNotFound()
        session = stripe.checkout.Session.retrieve(session_id)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        order = get_object_or_404(OrderDetail, stripe_payment_intent = session.payment_intent)
        order.has_paid = True
        order.save()
        return render(request, self.template_name)
    
class PaymentFailedView(TemplateView):
    template_name = "SiteApp/payment_failed.html"

#def mainpage(request):
 #   return HttpResponse("Главная страница")

taskmanager/SiteApp/templates/SiteApp/additem.html
{% extends "SiteApp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-blue-500">Add New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-black-500 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-black-500" type="text" placeholder="Name..." name="name" id="name">
            
            <label class="block text-black-500 text-md font-bold mb-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-black-500" type="text" placeholder="Price..." name="price" id="price">
            
            <label class="block text-black-500 text-md font-bold mb-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-black-500" type="text" placeholder="Description..." name="description" id="description">
            
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            
            <button class="block bg-green-400 text-black p-3 mt-4" type="submit" name="ADD Item" value="ADD Item">ADD Item</button>
        </div>
    </form>
</div>
{% endblock content %}

taskmanager/SiteApp/templates/SiteApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'SiteApp/styles.css' %}">
    <title>Document</title>
</head>
<body>
    
    {% include "SiteApp/navbar.html"%}

    {% block content %}
            TEXT
    {% endblock content %}
</body>
</html>

taskmanager/SiteApp/templates/SiteApp/deleteitem.html
{% extends "SiteApp/base.html" %}

{% block content %}
    <h1 class="text-2xl m-10 font bold">Delete Product </h1>
    <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-black text-sm font mb-2" for="">Are you sure you want to delete this product</label>
            <label class="block text-black text-sm font mb-2" for="">{{ item.name }}</label>
            <img class="w-1/3 h-[200px]" src="{{item.image.url}}" alt="" srcset="">
        </div>
        <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
        <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'SiteApp:index' %}">Cancel</a>
    </form>
{% endblock content %}

taskmanager/SiteApp/templates/SiteApp/detail.html
{% extends "SiteApp/base.html" %}
{% load humanize %}

{% block content %}
<div class="flex p-10 w-full h-200">
    <img class="w-1/3 h-[200px]" src="{{item.image.url}}" alt="itemPhoto">
    <div class="w-2/3 text-xl ml-10 mt-5">
        <p class="mt-5">  {{item.name}}</p>
        <p class="mt-5 text-blue-500">  Цена: {{item.price | intcomma }}</p>
        <p class="mt-5 text-black-500">  {{item.description}}</p>
        <p class="mt-5 text-black-500"><a href="{% url 'users:sellerprofile' item.id %}">@{{item.seller}}</a></p>
        <p class="mt-5 text-black-500">{{item.seller.profile.contact_number}}</p>
        <button class="bg-green-500 text-black mt-[50px]"><a href="{% url 'SiteApp:update_item' item.id %}">Update Item</a></button>
        <button class="bg-red-500 text-black mt-[50px]"><a href="{% url 'SiteApp:delete_item' item.id %}">Delete Item</a></button>
        <button class="bg-green-500 text-black mt-[50px]" id="checkout">Checkout</button>
    </div>
</div>
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
    var stripe = Stripe('{{stripe_publishable_key}}')
    var checkoutButton = document.getElementById('checkout')
    checkoutButton.addEventListener('click', function(){
        fetch("{% url 'SiteApp:api_checkout_session' id=item.id %}", {method: 'POST',})
        .then(function (response) {
            return response.json()
        })
        .then(function nae(session){
            return stripe.redirectToCheckout({sessionId:session.sessionId})
        })
        .then(function(result){
            if (result.error){
                alert(result.error.message)
            }
        })
        .catch(function(error){
            console.log('Error', error);
            
        })
    })
</script>
{% endblock content %}

taskmanager/SiteApp/templates/SiteApp/index.html
{% extends "SiteApp/base.html" %}
{% load humanize %}

{% block content %}
<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-black-500 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Топ товары</span>
            <span class="block xl:inline text-red-500">Акция</span>
        </h1>
        <p class="mt-3 text-base text-green-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Наша задача делать людей счастливее.</p>
    </div>

    <div class="mt-5 p-10 justify-center">
        <h2>Search</h2>
        <form action="" method="get">
            <input type="text" name="search" id="">
        </form>
    </div>

    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-3">
        {% for item in items %}
        <a href="{% url 'SiteApp:detail' item.id %}">
            <div class="rounded overflow-hidden shadow-lg">
                <img class="w-full h-[230px]" src="{{item.image.url}}" alt="">
                <div class="px-6 py-4">
                    <p class="font-bold text-xl mb-2">{{item.name}}</p>
                    <p class="font-bold text-xl text-blue-500 mb-2">Цена: {{item.price | intcomma}}</p>
                    <p class="font-bold text-xl text-indogo-500 mb-2">by: {{item.seller}}</p>
                    <p class="text-black-500 text-base">{{item.description}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
        <div>
            <span>
                {% if page_obj.has_previous %}
                    <a href="?page=1">First</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
            </span>
            <span>
                {{ page_obj }}
            </span>
            <span>
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
            </span>
        </div>
    </div>
</main>

{% endblock content %}

taskmanager/SiteApp/templates/SiteApp/navbar.html
{% load static %}
<nav class="bg-white shadow-lg"> 
    <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
            <div class="flex space-x-7">
                <div>
                    <a href="{% url 'SiteApp:index' %}" class="flex items-center px-2 py-4">
                    <img class="h-8 w-8" src="{% static 'SiteApp/images/shop.png' %}" alt="logo" />
                    <span class="text-blue-500 font-semibold text-xl">Good Shop</span>
                </a>
                </div>
                <div class="items-center flex space-x-1">
                    <a href="{% url 'SiteApp:index' %}" class="py-4 px-2 text-black-500 font-semibold border-b-4 border-yellow-400">Home</a>
                    <a href="#" class="py-4 px-2 text-black-500 font-semibold">About</a>
                    <a href="#" class="py-4 px-2 text-black-500 font-semibold">Contacts</a>
                    {% if user.is_authenticated %}
                        <a class="py-4 px-2 text-black-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                        <a method="post" class="py-4 px-2 text-black-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                        <a class="py-4 px-2 text-black-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>

taskmanager/SiteApp/templates/SiteApp/payment_failed.html
{% extends "SiteApp/base.html" %}

{% block content %}
    <p>Payment failed</p>
{% endblock content %}

taskmanager/SiteApp/templates/SiteApp/payment_success.html
{% extends "SiteApp/base.html" %}

{% block content %}
    <p>You have successfully paid</p>
{% endblock content %}

taskmanager/SiteApp/templates/SiteApp/product_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>Do you want to delete {{ object }}</p>
    <input type="submit" value="Delete">

</form>

taskmanager/SiteApp/templates/SiteApp/updateitem.html
{% extends "SiteApp/base.html" %}

{% block content %}

    <div class="ml-[200px]">
        <h1 class="text-2xl m-10 font-bold text-blue-500"> Update New Item</h1>
        <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="mb-4 ">
                <label class="block text-black-500 text-md font-bold mb-2" for="name">Item Name</label>
                <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-black-500" value="{{ item.name }}" type="text" placeholder="Name..." name="name" id="name">
                <label class="block text-black-500 text-md font-bold mb-2" for="price">Item Price</label>
                <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-black-500" value="{{ item.price }}" type="text" placeholder="Price..." name="price" id="price">
                <label class="block text-black-500 text-md font-bold mb-2" for="description">Item Description</label>
                <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-black-500" value="{{ item.description }}" type="text" placeholder="Description..." name="description" id="description">
                <img class="w-10 h-5" src="{{item.image.url}}" alt="" srcset="">
                <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
                <button class="block bg-gray-400 text-black p-3 mt-4" type="submit" name="ADD Item" value="ADD Item">Update Item</button>
            </div>
        </form>
    </div>

{% endblock content %}